CREATE TABLE poker_user (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    username VARCHAR(100) NOT NULL,
    profile_url TEXT,
    role VARCHAR(32) NOT NULL DEFAULT 'USER',
    bank_name VARCHAR(255),
    account_number VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    last_daily_bonus TIMESTAMP,
    avatar TEXT,
    avatar_border TEXT,
    cgp_score INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_poker_user_email UNIQUE (email),
    CONSTRAINT uk_poker_user_username UNIQUE (username),
    CONSTRAINT chk_poker_user_role CHECK (role IN ('USER', 'ADMIN', 'MODERATOR', 'SUPER_ADMIN', 'BOT'))
);

CREATE TABLE poker_user_balance (
    user_id INTEGER PRIMARY KEY REFERENCES poker_user(user_id) ON DELETE CASCADE,
    balance INTEGER NOT NULL DEFAULT 0,
    locked_amount INTEGER NOT NULL DEFAULT 0,
    bonus_balance INTEGER NOT NULL DEFAULT 0,
    last_bonus_session_id VARCHAR(128),
    CONSTRAINT chk_poker_user_balance_non_negative CHECK (
        balance >= 0
        AND locked_amount >= 0
        AND bonus_balance >= 0
    )
);

CREATE TABLE poker_table (
    table_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(255) NOT NULL,
    max_players INTEGER NOT NULL,
    big_blind INTEGER NOT NULL,
    small_blind INTEGER NOT NULL,
    min_buy_in INTEGER NOT NULL,
    max_buy_in INTEGER NOT NULL,
    variant VARCHAR(32) NOT NULL DEFAULT 'TEXAS',
    rake_percent NUMERIC(8, 6) NOT NULL DEFAULT 0.010000,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES poker_user(user_id),
    secure_id VARCHAR(64) UNIQUE,
    CONSTRAINT chk_poker_table_players CHECK (max_players > 0),
    CONSTRAINT chk_poker_table_blinds CHECK (big_blind > 0 AND small_blind > 0 AND small_blind <= big_blind),
    CONSTRAINT chk_poker_table_buy_in CHECK (min_buy_in > 0 AND max_buy_in >= min_buy_in),
    CONSTRAINT chk_poker_table_rake CHECK (rake_percent >= 0)
);

CREATE TABLE poker_game_session (
    session_id VARCHAR(128) PRIMARY KEY,
    table_id INTEGER NOT NULL,
    create_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE poker_hand_history (
    hand_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id INTEGER NOT NULL,
    hand_number BIGINT NOT NULL,
    winner_user_id INTEGER REFERENCES poker_user(user_id),
    winner_username VARCHAR(100) NOT NULL,
    winning_hole_cards JSONB NOT NULL,
    winning_community_cards JSONB NOT NULL,
    winnings INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_poker_hand_history_winner UNIQUE (table_id, hand_number, winner_user_id)
);

CREATE TABLE poker_chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT,
    user_id INTEGER REFERENCES poker_user(user_id) ON DELETE SET NULL,
    username VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE poker_deposit (
    deposit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES poker_user(user_id) ON DELETE CASCADE,
    admin_id INTEGER REFERENCES poker_user(user_id) ON DELETE SET NULL,
    amount INTEGER NOT NULL,
    type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    denied_reason TEXT,
    details JSONB NOT NULL DEFAULT '{}',
    create_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_date TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_poker_deposit_amount CHECK (amount > 0),
    CONSTRAINT chk_poker_deposit_type CHECK (type IN ('CASH', 'BANK_TRANSFER', 'GIFT')),
    CONSTRAINT chk_poker_deposit_status CHECK (status IN ('PENDING', 'APPROVED', 'DENIED'))
);

CREATE TABLE poker_withdrawal (
    withdrawal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES poker_user(user_id) ON DELETE CASCADE,
    amount INTEGER NOT NULL,
    create_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_by INTEGER REFERENCES poker_user(user_id) ON DELETE SET NULL,
    approve_date TIMESTAMP WITH TIME ZONE,
    details JSONB NOT NULL DEFAULT '{}',
    CONSTRAINT chk_poker_withdrawal_amount CHECK (amount > 0)
);

CREATE TABLE poker_outcome (
    outcome_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES poker_user(user_id) ON DELETE CASCADE,
    amount INTEGER NOT NULL,
    type VARCHAR(64) NOT NULL,
    game_session_id BIGINT,
    is_accounted BOOLEAN NOT NULL DEFAULT FALSE,
    create_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    account_date TIMESTAMP WITH TIME ZONE
);

CREATE TABLE poker_data_block (
    name VARCHAR(128) PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE poker_jackpot (
    jackpot_id INTEGER PRIMARY KEY DEFAULT 1,
    current_amount NUMERIC(19, 2) NOT NULL DEFAULT 0,
    seed_amount NUMERIC(19, 2) NOT NULL DEFAULT 0,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_poker_jackpot_singleton CHECK (jackpot_id = 1),
    CONSTRAINT chk_poker_jackpot_amounts CHECK (current_amount >= 0 AND seed_amount >= 0)
);

INSERT INTO poker_jackpot (jackpot_id, current_amount, seed_amount)
VALUES (1, 0, 0);

CREATE INDEX idx_poker_game_session_table_date ON poker_game_session(table_id, create_date DESC);
CREATE INDEX idx_poker_hand_history_table_date ON poker_hand_history(table_id, created_at DESC);
CREATE INDEX idx_poker_chat_message_table_date ON poker_chat_message(table_id, created_at DESC);
CREATE INDEX idx_poker_deposit_user_date ON poker_deposit(user_id, create_date DESC);
CREATE INDEX idx_poker_withdrawal_user_date ON poker_withdrawal(user_id, create_date DESC);
CREATE INDEX idx_poker_outcome_user_accounted ON poker_outcome(user_id, is_accounted);
